version: '3.8'

services:
  web:
    build: .
    command: gunicorn social_connect.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./social_connect:/app
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=social_connect_db
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=AZaz09$$

  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: AZaz09$$
      MYSQL_DATABASE: social_connect_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: